name: Build and Test create-gha-oidc-token action

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: Action Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
        - name: setup node
          uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
       
        - name: Install dependency
          run: |
            npm ci
        
        - name: Build
          run: |
            npm run build
        
        - name: Test Run
          uses: ./
          id: test
          with: 
            provider-endpoint: ${{ vars.PROVIDER_ENDPOINT }}
            app-id: ${{ vars.APP_ID }}
        
        - name: Token available
          uses: octokit/request-action@05a2312de9f8207044c4c9e41fe19703986acc13 # v2.x
          id: get-repository
          env:
            GITHUB_TOKEN: ${{ steps.test.outputs.token }}
          with:
            route: GET /installation/repositories
        
        - run: echo '${{ steps.get-repository.outputs.data }}'

        - name: Commit Test
          env: 
            GH_TOKEN: ${{ steps.test.outputs.token }}
          run: |
            gh auth setup-git
            git config user.name ${{ steps.test.outputs.app_slug }}
            git config user.email ${{ steps.test.outputs.commitemail }}

            git clone https://github.com/atolycs/empty-commit-test.git

            cd empty-commit-test

            git commit --allow-empty -m "feat: commit user test! ${{ github.workflow_sha }}"

            git push 